# Generated by Django 4.1.4 on 2022-12-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gempa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam', models.TimeField(blank=True, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('lintang', models.CharField(blank=True, max_length=100, null=True)),
                ('bujur', models.CharField(blank=True, max_length=100, null=True)),
                ('magnitudo', models.CharField(blank=True, max_length=100, null=True)),
                ('kedalaman', models.CharField(blank=True, max_length=100, null=True)),
                ('wilayah', models.CharField(blank=True, max_length=100, null=True)),
                ('potensi', models.CharField(blank=True, max_length=100, null=True)),
                ('dirasakan', models.CharField(blank=True, max_length=100, null=True)),
                ('shakemap', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuaca.kategori')),
            ],
        ),
    ]
