# Generated by Django 4.1.4 on 2022-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gempa',
            name='tanggal',
            field=models.DateField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
