# Generated by Django 4.1.4 on 2022-12-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0003_alter_gempa_tanggal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gempa',
            name='dirasakan',
        ),
        migrations.RemoveField(
            model_name='gempa',
            name='shakemap',
        ),
        migrations.AlterField(
            model_name='gempa',
            name='potensi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gempa',
            name='tanggal',
            field=models.DateField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gempa',
            name='wilayah',
            field=models.TextField(blank=True, null=True),
        ),
    ]
