# Generated by Django 4.1.4 on 2022-12-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0004_remove_gempa_dirasakan_remove_gempa_shakemap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gempa',
            name='tanggal',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
