# Generated by Django 4.1.4 on 2022-12-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0005_alter_gempa_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gempa',
            name='tanggal',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
