# Generated by Django 4.1.4 on 2022-12-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0006_alter_gempa_tanggal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuaca',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('propinsi', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('kecatamatan', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
            ],
        ),
    ]
