# Generated by Django 4.1.4 on 2022-12-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0007_cuaca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuaca',
            old_name='kecatamatan',
            new_name='kecamatan',
        ),
    ]
