# Generated by Django 4.1.4 on 2022-12-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0008_rename_kecatamatan_cuaca_kecamatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='isi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
