# Generated by Django 4.1.4 on 2022-12-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0009_artikel_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gempa',
            name='dirasakan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gempa',
            name='shakemap',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
