# Generated by Django 4.1.4 on 2022-12-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0010_gempa_dirasakan_gempa_shakemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gempa',
            name='jam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
